name: CI

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: echo command
        run: echo hello action!

      - name: Install SSH Client
        run: sudo apt install -y openssh-client

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{secrets.OCI_SSH_KEY}}

      - name: Deploy to OCI
        run: |
          ssh -tt -o StrictHostKeyChecking=no ${{secrets.OCI_USER}}@${{secrets.OCI_PUBLIC_IP}} << 'EOF'
            echo "Checking if the directory exists and if it's a valid Git repository..."
            if [ ! -d "/home/ubuntu/MyCICDTest/.git" ]; then
              echo "Directory not a Git repository. Cloning the repository..."
              rm -rf /home/ubuntu/MyCICDTest
              mkdir -p /home/ubuntu/MyCICDTest
              cd /home/ubuntu/MyCICDTest
              git clone https://github.com/jay5693/MyCICDTest.git .
            else
              echo "Git repository exists. Pulling latest changes..."
              cd /home/ubuntu/MyCICDTest
              git pull origin master
            fi

            echo "Checking if hello.py exists before running..."
            if [ -f "/home/ubuntu/MyCICDTest/hello.py" ]; then
              echo "Running Python script..."
              python3 /home/ubuntu/MyCICDTest/hello.py
            else
              echo "hello.py not found!"
            fi
          EOF
