name: CI

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: echo command
        run: echo hello action!

      - name: Install SSH Client
        run: sudo apt install -y openssh-client

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{secrets.OCI_SSH_KEY}}

      - name: Deploy to OCI
        run: |
          ssh -t -o StrictHostKeyChecking=no ${{secrets.OCI_USER}}@${{secrets.OCI_PUBLIC_IP}} << 'EOF'
            # Check if directory exists and clone repo if not
            if [ ! -d "/home/ubuntu/MyCICDTest" ]; then
              cd /home/ubuntu
              mkdir -p MyCICDTest
              cd MyCICDTest
              git clone https://github.com/your-repository.git .
            else
              cd /home/ubuntu/MyCICDTest
              git pull origin master
            fi

            # Run Python script (use python3)
            if command -v python3 &> /dev/null; then
              python3 hello.py
            else
              echo "Python3 is not installed, installing now..."
              sudo apt-get update && sudo apt-get install -y python3
              python3 hello.py
            fi
          EOF
